# Generated by Django 5.0.3 on 2026-03-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Day2', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completed_image',
            field=models.ImageField(blank=True, null=True, upload_to='completed_images/'),
        ),
        migrations.AddField(
            model_name='todo',
            name='thumbnail',
            field=models.ImageField(blank=True, default='thumbnails/default.png', null=True, upload_to='thumbnails/'),
        ),
    ]
